### ISSUE TITLE
Create PR Checklist Template

### ISSUE THREAD

**Issue by bms63** [Roche-GSK/admiral#786]
This template will provide a simple checklist for developers to mull over before submitting an official Pull Request.  The checklist will help remind new and old developers of some of the tasks needed to complete before doing a Pull Request.  For example, I always forget to update `news.md`!!   Ideally, the checklist will prevent an official Pull Request until the author has checked off every box in an acknowledgement that they have completed the task.  

I think this will be especially nice for new developers coming onto the project!

Please see the following templates for other Github projects that have made use of this feature:

1.  https://jemurai.com/2019/08/15/github-pr-checklist/
2.  https://stackoverflow.com/questions/25272215/how-to-automatically-add-a-checklist-to-new-github-prs

Additional internal discussion around this issue can be found here:
#765 

## The ASK from you

Can you add to the checklist?? - it can be a nit and gritty task to more general  task- e.g. update news.md versus update unit tests or write new unit tests.

## The PR Template so far (22-DEC-2021)

Thank you for your Pull Request!  We have developed this simple task checklist from the [Development Process Guide](https://roche-gsk.github.io/admiral/articles/development_process.html) to help with the final steps of the process.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Update unit tests or write new unit tests - See [Unit Test Guide](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::documents() ` so all `.Rd, NAMESPACE and DESCRIPTION` files are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://roche-gsk.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run Check Package locally and address all errors and warnings - ` devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 

Many thanks for your contribution to admiral!  

#### Template Changelog

- [ ] @bundfussr Updated based on site build and ordering.  Let me know if anything should be moved around
- [ ] @rossfarrugia Updated based on the Development Process Article

**Comment by bms63** [comment]
FYI - this is different than the automated github actions that check a lot of this stuff - this is to help head off errors from those actions and help minimize time reviewers have to spend on checking some of this stuff, e.g. unit tests written, updated vignetters, etc..

**Comment by bundfussr** [comment]
Great idea!

I would add
- [ ] Build site (`pkgdown::build_site()`) and check that all affected examples are displayed correctly and that all new functions occur  on the "Reference" page.

I would reorder the items of the list such that the ones updating source files come first, then the checks, and solving merge conflicts at the end.

**Comment by bms63** [comment]
@thomas-neitmann, @bundfussr @rossfarrugia and others

I got this set up in a personal github repo. https://github.com/bms63/pr_template_demo/pull/6

The steps are:

1) Set up `.github/pull_request_template.md`
2) Put our agreed upon tasks into the template along with any other guidance
3) Install Task List Completed App from Github Marketplace - https://github.com/marketplace/task-list-completed (FREE!)
4) Go!

![image](https://user-images.githubusercontent.com/10111024/146990748-ab54bd5a-4ff7-40ae-a878-820eb86977b8.png)

![image](https://user-images.githubusercontent.com/10111024/146990858-59fa585a-e19d-4e34-9d48-7341576dea0a.png)

**Comment by rossfarrugia** [comment]
great idea @bms63! any chance you can match the texts and order from a-g of https://github.com/Roche-GSK/admiral/blob/devel/vignettes/development_process.Rmd (see https://github.com/Roche-GSK/admiral/pull/777)? this is the new vignette that people should refer to when developing. feel free to update this with any extra checks i missed. important that the above and this vignette stay consistent so as not to confuse people.

i'm off from now for christmas hols, but happy to pick up any review or support needed when back early Jan. thanks!

**Comment by thomas-neitmann** [comment]
Great stuff @bms63 👏 

I agree with @rossfarrugia's comment that we should kkep this check list in sync with the Development Process vignette.

Apart from that, the current wording seems to be directed towards the developer who opened the PR rather than the reviewer. While the developer can certainly use this checklist it's the reviewer who will tick if off so I think the wording needs to reflect that.

**Comment by thomas-neitmann** [comment]
Btw, while we're talking about templates, do we also want to add an **issue template**?

**Comment by bundfussr** [comment]
I thought the developer would tick off the checklist before requesting review.

In principle an issue template is a good idea but the tricky point is the content. We could add checklist items for adding at least one label and setting the project. I am not sure what else could be useful and common for all issues.

**Comment by millerg23** [comment]
This looks great, excellent work @bms63. This would have helped me enormously!
I also think the checklist is for the developer.

Regarding issue template, I think its worth doing, but as Stefan suggests it could be quite a short list of things.
Only other possible things I can think of for issue template is:

Linking pull request to issue?
Remembering to move issue to correct state ie, 'In Progress', etc.?

**Comment by bms63** [comment]
@thomas-neitmann I was thinking the PR Checklist was for the developer and to help minimize the reviewers time spent on these types of task.  We could have two sections in the template - One for Developers and One for Reviewers.  I'd imagine they would be pretty similar, but these simple reminders could be very helpful!  Who doesn't want that green check mark!!

@rossfarrugia I reordered the task list according to the dev process article and linked it in the template.

I still haven't figured out how to add the Rule to the branch for the checklist.  Apparently you can prevent the merging until all items in the checklist are completed - like the R-CMD checks.  Right now you can still merge, but you will have a red X if you didn't check everything off.  

I am going to make a separate issue for the Issue Template.

**Comment by thomas-neitmann** [comment]
@bms63 I can edit the branch protection settings such that merging to `devel` and/or `master` is blocked unless the checklist is completed.
